// eslint-disable
export const contributors = [
  {
    login: 'bautistaaa',
    id: 3660667,
    node_id: 'MDQ6VXNlcjM2NjA2Njc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3660667?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/bautistaaa',
    html_url: 'https://github.com/bautistaaa',
    followers_url: 'https://api.github.com/users/bautistaaa/followers',
    following_url: 'https://api.github.com/users/bautistaaa/following{/other_user}',
    gists_url: 'https://api.github.com/users/bautistaaa/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/bautistaaa/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/bautistaaa/subscriptions',
    organizations_url: 'https://api.github.com/users/bautistaaa/orgs',
    repos_url: 'https://api.github.com/users/bautistaaa/repos',
    events_url: 'https://api.github.com/users/bautistaaa/events{/privacy}',
    received_events_url: 'https://api.github.com/users/bautistaaa/received_events',
    type: 'User',
    site_admin: false,
    contributions: 58,
  },
  {
    login: 'PickleNik',
    id: 31113245,
    node_id: 'MDQ6VXNlcjMxMTEzMjQ1',
    avatar_url: 'https://avatars.githubusercontent.com/u/31113245?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/PickleNik',
    html_url: 'https://github.com/PickleNik',
    followers_url: 'https://api.github.com/users/PickleNik/followers',
    following_url: 'https://api.github.com/users/PickleNik/following{/other_user}',
    gists_url: 'https://api.github.com/users/PickleNik/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/PickleNik/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/PickleNik/subscriptions',
    organizations_url: 'https://api.github.com/users/PickleNik/orgs',
    repos_url: 'https://api.github.com/users/PickleNik/repos',
    events_url: 'https://api.github.com/users/PickleNik/events{/privacy}',
    received_events_url: 'https://api.github.com/users/PickleNik/received_events',
    type: 'User',
    site_admin: false,
    contributions: 56,
  },
  {
    login: 'Hacksore',
    id: 996134,
    node_id: 'MDQ6VXNlcjk5NjEzNA==',
    avatar_url: 'https://avatars.githubusercontent.com/u/996134?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Hacksore',
    html_url: 'https://github.com/Hacksore',
    followers_url: 'https://api.github.com/users/Hacksore/followers',
    following_url: 'https://api.github.com/users/Hacksore/following{/other_user}',
    gists_url: 'https://api.github.com/users/Hacksore/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Hacksore/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Hacksore/subscriptions',
    organizations_url: 'https://api.github.com/users/Hacksore/orgs',
    repos_url: 'https://api.github.com/users/Hacksore/repos',
    events_url: 'https://api.github.com/users/Hacksore/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Hacksore/received_events',
    type: 'User',
    site_admin: false,
    contributions: 50,
  },
  {
    login: 'jhechtf',
    id: 8152471,
    node_id: 'MDQ6VXNlcjgxNTI0NzE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/8152471?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jhechtf',
    html_url: 'https://github.com/jhechtf',
    followers_url: 'https://api.github.com/users/jhechtf/followers',
    following_url: 'https://api.github.com/users/jhechtf/following{/other_user}',
    gists_url: 'https://api.github.com/users/jhechtf/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jhechtf/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jhechtf/subscriptions',
    organizations_url: 'https://api.github.com/users/jhechtf/orgs',
    repos_url: 'https://api.github.com/users/jhechtf/repos',
    events_url: 'https://api.github.com/users/jhechtf/events{/privacy}',
    received_events_url: 'https://api.github.com/users/jhechtf/received_events',
    type: 'User',
    site_admin: false,
    contributions: 16,
  },
  {
    login: 'ggrandi',
    id: 49359646,
    node_id: 'MDQ6VXNlcjQ5MzU5NjQ2',
    avatar_url: 'https://avatars.githubusercontent.com/u/49359646?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ggrandi',
    html_url: 'https://github.com/ggrandi',
    followers_url: 'https://api.github.com/users/ggrandi/followers',
    following_url: 'https://api.github.com/users/ggrandi/following{/other_user}',
    gists_url: 'https://api.github.com/users/ggrandi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ggrandi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ggrandi/subscriptions',
    organizations_url: 'https://api.github.com/users/ggrandi/orgs',
    repos_url: 'https://api.github.com/users/ggrandi/repos',
    events_url: 'https://api.github.com/users/ggrandi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/ggrandi/received_events',
    type: 'User',
    site_admin: false,
    contributions: 15,
  },
  {
    login: 'creativenull',
    id: 3767728,
    node_id: 'MDQ6VXNlcjM3Njc3Mjg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3767728?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/creativenull',
    html_url: 'https://github.com/creativenull',
    followers_url: 'https://api.github.com/users/creativenull/followers',
    following_url: 'https://api.github.com/users/creativenull/following{/other_user}',
    gists_url: 'https://api.github.com/users/creativenull/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/creativenull/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/creativenull/subscriptions',
    organizations_url: 'https://api.github.com/users/creativenull/orgs',
    repos_url: 'https://api.github.com/users/creativenull/repos',
    events_url: 'https://api.github.com/users/creativenull/events{/privacy}',
    received_events_url: 'https://api.github.com/users/creativenull/received_events',
    type: 'User',
    site_admin: false,
    contributions: 14,
  },
  {
    login: 'ernestoresende',
    id: 55156145,
    node_id: 'MDQ6VXNlcjU1MTU2MTQ1',
    avatar_url: 'https://avatars.githubusercontent.com/u/55156145?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ernestoresende',
    html_url: 'https://github.com/ernestoresende',
    followers_url: 'https://api.github.com/users/ernestoresende/followers',
    following_url: 'https://api.github.com/users/ernestoresende/following{/other_user}',
    gists_url: 'https://api.github.com/users/ernestoresende/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ernestoresende/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ernestoresende/subscriptions',
    organizations_url: 'https://api.github.com/users/ernestoresende/orgs',
    repos_url: 'https://api.github.com/users/ernestoresende/repos',
    events_url: 'https://api.github.com/users/ernestoresende/events{/privacy}',
    received_events_url: 'https://api.github.com/users/ernestoresende/received_events',
    type: 'User',
    site_admin: false,
    contributions: 9,
  },
  {
    login: 'is-it-ayush',
    id: 36449128,
    node_id: 'MDQ6VXNlcjM2NDQ5MTI4',
    avatar_url: 'https://avatars.githubusercontent.com/u/36449128?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/is-it-ayush',
    html_url: 'https://github.com/is-it-ayush',
    followers_url: 'https://api.github.com/users/is-it-ayush/followers',
    following_url: 'https://api.github.com/users/is-it-ayush/following{/other_user}',
    gists_url: 'https://api.github.com/users/is-it-ayush/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/is-it-ayush/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/is-it-ayush/subscriptions',
    organizations_url: 'https://api.github.com/users/is-it-ayush/orgs',
    repos_url: 'https://api.github.com/users/is-it-ayush/repos',
    events_url: 'https://api.github.com/users/is-it-ayush/events{/privacy}',
    received_events_url: 'https://api.github.com/users/is-it-ayush/received_events',
    type: 'User',
    site_admin: false,
    contributions: 8,
  },
  {
    login: 'basokant',
    id: 70033855,
    node_id: 'MDQ6VXNlcjcwMDMzODU1',
    avatar_url: 'https://avatars.githubusercontent.com/u/70033855?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/basokant',
    html_url: 'https://github.com/basokant',
    followers_url: 'https://api.github.com/users/basokant/followers',
    following_url: 'https://api.github.com/users/basokant/following{/other_user}',
    gists_url: 'https://api.github.com/users/basokant/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/basokant/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/basokant/subscriptions',
    organizations_url: 'https://api.github.com/users/basokant/orgs',
    repos_url: 'https://api.github.com/users/basokant/repos',
    events_url: 'https://api.github.com/users/basokant/events{/privacy}',
    received_events_url: 'https://api.github.com/users/basokant/received_events',
    type: 'User',
    site_admin: false,
    contributions: 5,
  },
  {
    login: 'emalineg',
    id: 93755103,
    node_id: 'U_kgDOBZaW3w',
    avatar_url: 'https://avatars.githubusercontent.com/u/93755103?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/emalineg',
    html_url: 'https://github.com/emalineg',
    followers_url: 'https://api.github.com/users/emalineg/followers',
    following_url: 'https://api.github.com/users/emalineg/following{/other_user}',
    gists_url: 'https://api.github.com/users/emalineg/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/emalineg/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/emalineg/subscriptions',
    organizations_url: 'https://api.github.com/users/emalineg/orgs',
    repos_url: 'https://api.github.com/users/emalineg/repos',
    events_url: 'https://api.github.com/users/emalineg/events{/privacy}',
    received_events_url: 'https://api.github.com/users/emalineg/received_events',
    type: 'User',
    site_admin: false,
    contributions: 4,
  },
  {
    login: 'FullStackCorm',
    id: 101738478,
    node_id: 'U_kgDOBhBn7g',
    avatar_url: 'https://avatars.githubusercontent.com/u/101738478?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/FullStackCorm',
    html_url: 'https://github.com/FullStackCorm',
    followers_url: 'https://api.github.com/users/FullStackCorm/followers',
    following_url: 'https://api.github.com/users/FullStackCorm/following{/other_user}',
    gists_url: 'https://api.github.com/users/FullStackCorm/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/FullStackCorm/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/FullStackCorm/subscriptions',
    organizations_url: 'https://api.github.com/users/FullStackCorm/orgs',
    repos_url: 'https://api.github.com/users/FullStackCorm/repos',
    events_url: 'https://api.github.com/users/FullStackCorm/events{/privacy}',
    received_events_url: 'https://api.github.com/users/FullStackCorm/received_events',
    type: 'User',
    site_admin: false,
    contributions: 4,
  },
  {
    login: 'F-PTS',
    id: 80021800,
    node_id: 'MDQ6VXNlcjgwMDIxODAw',
    avatar_url: 'https://avatars.githubusercontent.com/u/80021800?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/F-PTS',
    html_url: 'https://github.com/F-PTS',
    followers_url: 'https://api.github.com/users/F-PTS/followers',
    following_url: 'https://api.github.com/users/F-PTS/following{/other_user}',
    gists_url: 'https://api.github.com/users/F-PTS/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/F-PTS/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/F-PTS/subscriptions',
    organizations_url: 'https://api.github.com/users/F-PTS/orgs',
    repos_url: 'https://api.github.com/users/F-PTS/repos',
    events_url: 'https://api.github.com/users/F-PTS/events{/privacy}',
    received_events_url: 'https://api.github.com/users/F-PTS/received_events',
    type: 'User',
    site_admin: false,
    contributions: 3,
  },
  {
    login: 'metal-face',
    id: 101987676,
    node_id: 'U_kgDOBhQ1XA',
    avatar_url: 'https://avatars.githubusercontent.com/u/101987676?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/metal-face',
    html_url: 'https://github.com/metal-face',
    followers_url: 'https://api.github.com/users/metal-face/followers',
    following_url: 'https://api.github.com/users/metal-face/following{/other_user}',
    gists_url: 'https://api.github.com/users/metal-face/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/metal-face/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/metal-face/subscriptions',
    organizations_url: 'https://api.github.com/users/metal-face/orgs',
    repos_url: 'https://api.github.com/users/metal-face/repos',
    events_url: 'https://api.github.com/users/metal-face/events{/privacy}',
    received_events_url: 'https://api.github.com/users/metal-face/received_events',
    type: 'User',
    site_admin: false,
    contributions: 3,
  },
  {
    login: 'thecornisians',
    id: 84820874,
    node_id: 'MDQ6VXNlcjg0ODIwODc0',
    avatar_url: 'https://avatars.githubusercontent.com/u/84820874?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/thecornisians',
    html_url: 'https://github.com/thecornisians',
    followers_url: 'https://api.github.com/users/thecornisians/followers',
    following_url: 'https://api.github.com/users/thecornisians/following{/other_user}',
    gists_url: 'https://api.github.com/users/thecornisians/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/thecornisians/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/thecornisians/subscriptions',
    organizations_url: 'https://api.github.com/users/thecornisians/orgs',
    repos_url: 'https://api.github.com/users/thecornisians/repos',
    events_url: 'https://api.github.com/users/thecornisians/events{/privacy}',
    received_events_url: 'https://api.github.com/users/thecornisians/received_events',
    type: 'User',
    site_admin: false,
    contributions: 1,
  },
  {
    login: 'QuiiBz',
    id: 43268759,
    node_id: 'MDQ6VXNlcjQzMjY4NzU5',
    avatar_url: 'https://avatars.githubusercontent.com/u/43268759?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/QuiiBz',
    html_url: 'https://github.com/QuiiBz',
    followers_url: 'https://api.github.com/users/QuiiBz/followers',
    following_url: 'https://api.github.com/users/QuiiBz/following{/other_user}',
    gists_url: 'https://api.github.com/users/QuiiBz/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/QuiiBz/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/QuiiBz/subscriptions',
    organizations_url: 'https://api.github.com/users/QuiiBz/orgs',
    repos_url: 'https://api.github.com/users/QuiiBz/repos',
    events_url: 'https://api.github.com/users/QuiiBz/events{/privacy}',
    received_events_url: 'https://api.github.com/users/QuiiBz/received_events',
    type: 'User',
    site_admin: false,
    contributions: 1,
  },
];
