import { SignIn } from "@clerk/nextjs";
import { UserButton } from "@clerk/nextjs";

import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>asdasd</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <header>
          <UserButton afterSignOutUrl="/" />
        </header>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <SignIn />
        </div>
      </main>
    </>
  );
};

export default Home;
