import { Providers } from './providers';

import '../styles/globals.css';

import { Inter } from 'next/font/google';
import { Navigation } from '~/components/ui/navigation';
import { Toaster } from '~/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning>
      <head>
        <title>Type Hero</title>
        <meta
          name="description"
          content="Level up your typescript skills with interactive exercises"
        />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>
      <body className={`${inter.className} flex flex-col`}>
        <Providers>
          <Navigation />
          <main className="flex-1">
            <div className="container h-full">{children}</div>
          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
